### ISSUE TITLE
Using pretrained word embeddings

### ISSUE THREAD

**Issue by sanjaymeena** [dennybritz/cnn-text-classification-tf#17]
@dennybritz 

Hi , 
First of all many thanks for sharing your code.  I am trying to use pretrained word embeddings instead of randomly initialized word embedings based on the vocabulary size. 

My pretrained word embedding is numpy array  : ( N, 300, dtype=float.32) where N is indice of the word for which word embedding of dimension (300,) is stored. 

However , unable to pass the step of             
self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x) because tensorflow only allows int32,int64 as lookup indices. 

Can you suggest how can i resolve this issue? 

Many thanks

**Comment by dennybritz** [comment]
Sorry for the late reply, I was traveling. You need to set your pretrained embedding as the initializer of W when W is declared.

**Comment by fmaglia** [comment]
@sanjaymeena Can you share your code for the pre-training of word embeddings?

**Comment by sanjaymeena** [comment]
@fmaglia  I am posting snippet of code for  using pretrained word embeddings 

'''
from tensorflow.python.framework import ops
from tensorflow.python.ops import array_ops as array_ops_
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import nn
from tensorflow.python.ops import variable_scope as vs

class TextCNN(object):
    """
    A CNN for text classification.
    Uses an embedding layer, followed by a convolutional, max-pooling and softmax layer.
    """
    def __init__(
      self, sequence_length, num_classes, vocab_size,word_vector_map,
      embedding_size, filter_sizes, num_filters, l2_reg_lambda=0.0,embedding_type='static'):

        # Placeholders for input, output and dropout
        self.input_x = tf.placeholder(tf.int32, [None, sequence_length], name="input_x")
        self.input_y = tf.placeholder(tf.float32, [None, num_classes], name="input_y")
        self.dropout_keep_prob = tf.placeholder(tf.float32, name="dropout_keep_prob")

        # Keeping track of l2 regularization loss (optional)
        l2_loss = tf.constant(0.0)

        #Embedding layer
        #with tf.device('/cpu:0'), tf.name_scope("embedding"):
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
            
            # use pretrained word2vec embeddings 
            if embedding_type in 'static':
                ids=self.input_x
                embeddings = vs.get_variable('w2v' + "_embeddings",
                                         [num_classes, embedding_size])
                name="embedding_lookup"
                ids = ops.convert_to_tensor(ids)
                params=tf.Variable(word_vector_map)

                # shape 
                shape = array_ops_.shape(ids)

                # concatenates all the ids from all the sentences
                ids_flat = array_ops_.reshape(ids, math_ops.reduce_prod(shape, keep_dims=True))
                #
                embeds_flat = nn.embedding_lookup(params, ids_flat, name)
                embed_shape = array_ops_.concat(0, [shape, [-1]])
                embeds = array_ops_.reshape(embeds_flat, embed_shape)
                embeds.set_shape(ids.get_shape().concatenate(params.get_shape()[1:]))

                self.embedded_chars=embeds
                self.embedded_chars_expanded=tf.expand_dims(self.embedded_chars, -1)

                
            else:
                W = tf.Variable(
                    tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0),
                    name="W")

                self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
                self.embedded_chars_ex
'''

**Comment by j314erre** [comment]
Try initializing W from pre-trained vectors during the training session, not in the model definition. 


First, make your embedding a self variable in `__init__()` in text_cnn.py

```
                self.W = tf.Variable(
                    tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0),
                    name="W")

                self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
                self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)
```

Second, just initialized the W matrix from the word2vec file in train.py like this:

```
        sess.run(tf.initialize_all_variables())

    # initial matrix with random uniform
    init_W = np.random.uniform(-0.25,0.25,(input_size, embedding_size))
        
    # load any vectors from the word2vec
    with open(word2vec_path, "rb") as f:
        header = f.readline()
        vocab_size, layer1_size = map(int, header.split())
        binary_len = np.dtype('float32').itemsize * layer1_size
        for line in xrange(vocab_size):
            word = []
            while True:
                ch = f.read(1)
                if ch == ' ':
                    word = ''.join(word)
                    break
                if ch != '\n':
                    word.append(ch)   
            if word in vocab:
                idx = vocab[word]
                init_W[idx] = np.fromstring(f.read(binary_len), dtype='float32')  
            else:
                f.read(binary_len)    


           sess.run(cnn.W.assign(init_embedding))
```


hope this helps...

**Comment by fmaglia** [comment]
@sanjaymeena Thanks for the code.
I have 3 questions:
1) `TypeError: __init__() takes at least 8 arguments (9 given)` 
In the train.py I add `embedding_type` in the class instantiation
How I can solve this error?
2) In your code there are no steps in which word2vec access to a dataset for the pre-training. Why?
3) What you are using as dataset for the pre-training? Can you share it?

**Comment by ferfervi** [comment]
Hi @dennybritz , thanks for sharing your code! 

I am facing some issues when trying to use your CNN slightly modified using word2vec as an input, I will try to explain briefly what I have done:

- In train.py I modified the method that obtains the data  as "x"  implementing "data_helpers.get_input_as_word2vec() " using gensim word2vec.
- The dataset I am using IMDB as a dataset, being each row of "x" a movie review encoded as a word2vec vector with n_dim=300 (number of columns). After cross_validation, I obtain "x_train" ,finally getting the batches I obtain "x_batch". 
- "y_batch" is the label of the review: (1,0) or (0,1) same as you do.
- Every call to  "train_step(x_batch, y_batch)" as you do, it trains a batch of [n_reviews_batch_size, n_features_word2_vec]. The run method inside "train_step" will make accessible x_batch inside TextCNN.py object as "input_x" (being this a batch of reviews)

After several tries I haven't been able to attach the word2vec embegging to the CNN. I am not really familiar yet with TensorFlow and its notation. Could you please give me some hint? Thanks in advance!

The error I get:   TypeError("List of Tensors when single Tensor expected")

Here is the TextCNN code in which I try to define W where "input_x" is a list of tensors (one for each review in the batch [n_review_batch, n_dim_word2_vec] ):
```
    def __init__(
       self, sequence_length, num_classes, vocab_size,
       embedding_size, filter_sizes, num_filters, l2_reg_lambda):

        # (embedding_size = n_dim_word2vec = sequence_length )
        # Placeholders for input, output and dropout
        self.input_x = tf.placeholder(tf.int32, [None, sequence_length], name="input_x")
        self.input_y = tf.placeholder(tf.float32, [None, num_classes], name="input_y")
        self.dropout_keep_prob = tf.placeholder(tf.float32, name="dropout_keep_prob")

        # Keeping track of l2 regularization loss (optional)
        l2_loss = tf.constant(0.0)

        # Embedding layer 
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
            W = tf.constant(self.input_x, name="W",shape=[self.input_x.get_shape()[0], embedding_size])

            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

        # Create a convolution + maxpool layer for each filter size
        # ....


```

**Comment by ferfervi** [comment]
Hi @dennybritz 
Thank you for your sharing your code!  I am having some issue trying to user word2vec as input:

I have a pretrained word2vec matrix "embedding_matrix" with one text sentence per row and n_dim(300) columns using gensim.

- I assign it to "W" after defining it. However I get an error when processing "tf.nn.embedding_lookup(W, self.input_x)"
- I followed your indications assining the pretrained word2vec matrix using W.assign(). Please, let me know if you how to solve it. thanks in advance!  (Please, note that I am not really familiar yet with TensorFlow)
```
   # Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
           W = tf.Variable(tf.random_uniform([embedding_matrix.shape[0], embedding_size], -1.0, 1.0),name="W")
           W.assign(embedding_matrix)

            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

        # Create a convolution + maxpool layer for each filter size
        #...
```
- Error:

tensorflow.python.framework.errors.InvalidArgumentError: indices[0,10] = -1 is not in [0, 50000)
	 [[Node: embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/read, _recv_input_x_0)]]
Caused by op 'embedding/embedding_lookup', defined at:
 File "cnn-text-classification-tf/text_cnn.py", line 46, in __init__
    self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)

**Comment by Fjq** [comment]
@sanjaymeena what's the parameter "word_vector_map" mean, what's the format of it ?

**Comment by ngoduyvu** [comment]
Hi guys, I have the same problem with you guy. I tried to apply word2vec for Convolution Neural Network in Text Classification task. The code for pre_train is "word2vec_basic.py" in Tensorflow website. I really don't know how to feed it in the network. Here is the code I tried to do:

` W = tf.Variable(tf.constant(0.0, shape=[vocabulary_size, embedding_size]),
                trainable=False, name="W")

embedding_placeholder = tf.placeholder(tf.float32, [vocabulary_size, embedding_size])
embedding_init = W.assign(embedding_placeholder) `

**Comment by j314erre** [comment]
Here is how I load pre-trained word2vec into the model...


In text_cnn.py make W a self:
```

            self.W = tf.Variable(
                tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0),
                name="W")
```
In train.py add something like this after "# Initialize all variables"
```

    sess.run(tf.initialize_all_variables())

    # initial matrix with random uniform
    initW = np.random.uniform(-0.25,0.25,(input_size, 300))
    # load any vectors from the word2vec
    with open("GoogleNews-vectors-negative300.bin", "rb") as f:
        header = f.readline()
        vocab_size, layer1_size = map(int, header.split())
        binary_len = np.dtype('float32').itemsize * layer1_size
        for line in xrange(vocab_size):
            word = []
            while True:
                ch = f.read(1)
                if ch == ' ':
                    word = ''.join(word)
                    break
                if ch != '\n':
                    word.append(ch)   
            if word in vocab:
                idx = vocab_processor.vocabulary_.get(word)
                initW[idx] = np.fromstring(f.read(binary_len), dtype='float32')  
            else:
                f.read(binary_len)    
       
     session.run(cnn.W.assign(initW))

```

You'd need to run --embedding_dim=300 to match the word2vec

**Comment by ngoduyvu** [comment]
Hi j314erre, thanks for your code but I am quite don't understand it. Are all of your result stored in "GoogleNews-vectors-negative300.bin" ? My code is similar with "word2vec_basic.py" of Tensorflow. Could I use "cnn.W.assign" like you  ?

**Comment by j314erre** [comment]
My code example assumes pre-trained vectors are stored in the [Google format and you can get GoogleNews-vectors-negative300.bin here](https://code.google.com/archive/p/word2vec/) 

I believe for pre-trained vectors it makes more sense to load them from a file.

I haven't used word2vec_basic.py buy it looks like the basic idea would be to assign 'final_embeddings' into `session.run(cnn.W.assign(final_embeddings))`

**Comment by ngoduyvu** [comment]
Yeah that is exactly what I did


`W = tf.Variable(tf.constant(0.0, shape=[vocabulary_size, embedding_size]),
                trainable=False, name="W")

embedding_placeholder = tf.placeholder(tf.float32, [vocabulary_size, embedding_size])
embedding_init = W.assign(embedding_placeholder)


sess = tf.Session()

sess.run(embedding_init, feed_dict={embedding_placeholder: final_embeddings})

embedded_chars = tf.nn.embedding_lookup(W, data)
embedded_chars_expanded = tf.expand_dims(embedded_chars, -1)`

I used embedding_lookup for W and data (data is the variable store index of distionary) is It correct ? As @dennybritz wrote that "maps vocabulary word indices into low-dimensional vector representations"

**Comment by wsywsya119** [comment]
Hi @j314erre ! Thanks for your code.
I followed your code and fix train.py.
But got a error with embedding size and vocab_size
I had fix the embedding size to 300

May I ask that do I fix anything about the # build vocabulary in train.py?

**Comment by j314erre** [comment]
Here is a gist of modified text_cnn.py and train.py that loads pre-trained word2vec https://gist.github.com/j314erre/b7c97580a660ead82022625ff7a644d8

Note: you have to set --embedding_dim to be the same size as your pre-trained embeddings.

Also note:  it initializes the embedding with the pre-trained embeddings, but continues to learn and adapt the embeddings as you train further on your data...this is usually what you want.

I ran it like this:

```
$ ./train.py --embedding_dim=300 --word2vec=./GoogleNews-vectors-negative300.bin

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_EVERY=100
DROPOUT_KEEP_PROB=0.5
EMBEDDING_DIM=300
EVALUATE_EVERY=100
FILTER_SIZES=3,4,5
L2_REG_LAMBDA=0.0
LOG_DEVICE_PLACEMENT=False
NUM_EPOCHS=200
NUM_FILTERS=128
WORD2VEC=/mnt/hgfs/Temp/deeplearning/data/word2vec/GoogleNews-vectors-negative300.bin

Loading data...
Vocabulary Size: 18758
Train/Dev split: 9662/1000
Writing to /mnt/hgfs/Temp/deeplearning/github/cnn-text-classification-tf-word2vec/runs/1468367719

Load word2vec file /mnt/hgfs/Temp/deeplearning/data/word2vec/GoogleNews-vectors-negative300.bin

2016-07-12T16:56:02.915101: step 1, loss 2.184, acc 0.484375
2016-07-12T16:56:03.463751: step 2, loss 1.05255, acc 0.5625
2016-07-12T16:56:03.786084: step 3, loss 0.961079, acc 0.515625
2016-07-12T16:56:04.096605: step 4, loss 1.14572, acc 0.5
2016-07-12T16:56:04.405554: step 5, loss 1.56523, acc 0.46875
2016-07-12T16:56:04.708008: step 6, loss 1.50058, acc 0.484375
2016-07-12T16:56:05.014675: step 7, loss 1.25756, acc 0.546875
2016-07-12T16:56:05.386628: step 8, loss 1.25465, acc 0.5625
2016-07-12T16:56:05.688880: step 9, loss 1.05234, acc 0.421875
2016-07-12T16:56:06.013079: step 10, loss 0.964042, acc 0.59375
2016-07-12T16:56:06.328913: step 11, loss 1.07336, acc 0.5
2016-07-12T16:56:06.627696: step 12, loss 0.868269, acc 0.609375
2016-07-12T16:56:06.928440: step 13, loss 1.09265, acc 0.46875
2016-07-12T16:56:07.239481: step 14, loss 1.10638, acc 0.546875
2016-07-12T16:56:07.676407: step 15, loss 1.07905, acc 0.5
2016-07-12T16:56:08.095794: step 16, loss 1.0597, acc 0.484375
2016-07-12T16:56:08.404082: step 17, loss 1.00784, acc 0.5
2016-07-12T16:56:08.717828: step 18, loss 0.931868, acc 0.5625
2016-07-12T16:56:09.028319: step 19, loss 0.828277, acc 0.5625
2016-07-12T16:56:09.342007: step 20, loss 0.893648, acc 0.609375
2016-07-12T16:56:09.667044: step 21, loss 1.14949, acc 0.453125
2016-07-12T16:56:09.968128: step 22, loss 1.18135, acc 0.53125
2016-07-12T16:56:10.291308: step 23, loss 1.0197, acc 0.578125
2016-07-12T16:56:10.596666: step 24, loss 0.804317, acc 0.5625
2016-07-12T16:56:10.917560: step 25, loss 0.92725, acc 0.546875
2016-07-12T16:56:11.246497: step 26, loss 0.749425, acc 0.59375
2016-07-12T16:56:11.558792: step 27, loss 0.901106, acc 0.5625
2016-07-12T16:56:11.867418: step 28, loss 0.888104, acc 0.484375


```

**Comment by wsywsya119** [comment]
Hi @j314erre. 
I try your code to my fix version, it works!!
Thank you very much!!

**Comment by chaitjo** [comment]
Hey @j314erre, Thanks for this! What changes should I make to the code if I do not want the embeddings to continue to be trained along with the model? (i.e. I want to use static word2vec embeddings)

**Comment by j314erre** [comment]
I have not tested this but try `trainable=False` when you define those parameters:

```
# Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
            self.W = tf.Variable(
                tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0),
                trainable=False,
                name="W")
            self.embedded_chars = tf.nn.embedding_lookup(self.W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)
```

**Comment by cuixue** [comment]
@ferfervi  hello,I meet the same problem with you ,have you solved it?

**Comment by pldelisle** [comment]
@j314erre 
How much RAM you machine has to run this code ? I tried to load the Google binary file, but with 16 GB, I always get memory exhaustion errors :

```
root@f8d6a880db61:/mnt/chatbot/cnn/scripts# python3 train.py --embedding_dim=300 --version=1 --word2vec="/mnt/chatbot/data/GoogleNews-vectors-negative300.bin"

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_EVERY=100
DROPOUT_KEEP_PROB=0.5
EMBEDDING_DIM=300
EVALUATE_EVERY=100
FILTER_SIZES=3,4,5
L2_REG_LAMBDA=0.0
LOG_DEVICE_PLACEMENT=False
NUM_EPOCHS=100
NUM_FILTERS=128
WORD2VEC=/mnt/chatbot/data/GoogleNews-vectors-negative300.bin

Vocabulary Size: 2111
Training/Cross-validation/Test split: 7962/2654/2652
Writing to /mnt/chatbot/cnn/experiments/runs/1477599393

Load word2vec file /mnt/chatbot/data/GoogleNews-vectors-negative300.bin

Traceback (most recent call last):
 File "train.py", line 386, in <module>
   main(sys.argv[1:])
 File "train.py", line 239, in main
   word.append(ch)
MemoryError
```

My VM has 16 GB of RAM. I would like to know how much you have.

Thanks !

**Comment by krutarthjoshi18** [comment]
Hi @j314erre

Could you pls. let me know what's wrong with my code. I modified it in the same way and is running this way.

`Traceback (most recent call last):
  File "./train.py", line 141, in <module>
    if FLAGS.word2vec:
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 44, in __getattr__
    raise AttributeError(name)
AttributeError: word2vec
papio:cnn-text-classification-tf-master compbio$`

**Comment by andrisecker** [comment]
@dennybritz, @j314erre

Hi, thanks for the code!
I tried to run it with GloVe trained on the positive and negative examples, and I got an error from tf.nn.embedding_lookup():
`InvalidArgumentError (see above for traceback): indices[0,11] = 21161 is not in [0, 21161)
	 [[Node: embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/read, _recv_input_x_0)]] 
> 21161 is the number of the pretrained vectors (and I use a 21161 x embedding_size - matrix in the embedding layer for the weights) 

in the [documentation of the tf.nn.embedding_lookup_sparse()](http://devdocs.io/tensorflow~python/nn#embedding_lookup_sparse) they mention:  "It also assumes that all id values lie in the range [0, p0), where p0 is the sum of the size of params along dimension 0."
Why exactly should the id value be less than the size of params along dimension 0?
Is there any way to solve this?

**Comment by hariom-yadaw** [comment]
@dennybritz what is advantage of `pre-trained`embedding words ? I have  dataset(not very large). In test/validation dataset, I have some sentences with same meaning/context but sentence is not using exact same words. Then in that case acuuracy is not good. How to solve this issue ? Please help. I hope you have lots of ideas on this.

**Comment by Franck-Dernoncourt** [comment]
An interesting post written by [mrry](http://stackoverflow.com/users/3574081/mrry) on [Using a pre-trained word embedding (word2vec or Glove) in TensorFlow](http://stackoverflow.com/a/35688187/395857):

> 
> There are a few ways that you can use a pre-trained embedding in TensorFlow. Let's say that you have the embedding in a NumPy array called `embedding`, with `vocab_size` rows and `embedding_dim` columns and you want to create a tensor `W` that can be used in a call to [`tf.nn.embedding_lookup()`][1].
> 
> 1. Simply create `W` as a [`tf.constant()`][2] that takes `embedding` as its value:
> 
>         W = tf.constant(embedding, name="W")
> 
>    This is the easiest approach, but it is not memory efficient because the value of a `tf.constant()` is stored multiple times in memory. Since `embedding` can be very large, you should only use this approach for toy examples.
> 
> 2. Create `W` as a `tf.Variable` and initialize it from the NumPy array via a [`tf.placeholder()`][3]:
> 
>         W = tf.Variable(tf.constant(0.0, shape=[vocab_size, embedding_dim]),
>                         trainable=False, name="W")
> 
>         embedding_placeholder = tf.placeholder(tf.float32, [vocab_size, embedding_dim])
>         embedding_init = W.assign(embedding_placeholder)
> 
>         # ...
>         sess = tf.Session()
> 
>         sess.run(embedding_init, feed_dict={embedding_placeholder: embedding})
> 
>    This avoid storing a copy of `embedding` in the graph, but it does require enough memory to keep two copies of the matrix in memory at once (one for the NumPy array, and one for the `tf.Variable`). Note that I've assumed that you want to hold the embedding matrix constant during training, so `W` is created with `trainable=False`.
> 
> 3. If the embedding was trained as part of another TensorFlow model, you can use a [`tf.train.Saver`][4] to load the value from the other model's checkpoint file. This means that the embedding matrix can bypass Python altogether. Create `W` as in option 2, then do the following:
> 
>         W = tf.Variable(...)
>         
>         embedding_saver = tf.train.Saver({"name_of_variable_in_other_model": W})
> 
>         # ...
>         sess = tf.Session()
>         embedding_saver.restore(sess, "checkpoint_filename.ckpt")

  [1]: https://www.tensorflow.org/versions/r0.7/api_docs/python/nn.html#embedding_lookup
  [2]: https://www.tensorflow.org/versions/r0.7/api_docs/python/constant_op.html#constant
  [3]: https://www.tensorflow.org/versions/r0.7/api_docs/python/io_ops.html#placeholder
  [4]: https://www.tensorflow.org/versions/r0.7/api_docs/python/state_ops.html#Saver

**Comment by hariom-yadaw** [comment]
Thanks a lot @Franck-Dernoncourt! how does pretrained embedding is different from having the models' own embedding(created during training the model) ? Currently I have relatively small dataset to train on my model and wanted to get it generalized on new test examples in sense that chatbot understand different sentences carrying same semantic meaning(intents and entities in it). For example:

1. How can you help me?;  How can you assist me?; What assistance can you provide?; - Intent: help type
2. Make me laugh.; Crack some jokes  please.; Can you make me laugh?; Can you tell me something funny?; Can you entertain me? Please entertain me. ----> intent: Entertainment

What kind of embedding can help me on the above problem? Thanks.

**Comment by Franck-Dernoncourt** [comment]
@hariom-yadaw using pre-trained word embeddings, which are fine-tuned during the training phase, sometimes helps, e.g.  https://arxiv.org/pdf/1606.03475.pdf:

![image](https://cloud.githubusercontent.com/assets/15331/23311104/e10fc0fc-fa82-11e6-9cc4-7956f5eb39e6.png)

**Comment by hariom-yadaw** [comment]
@Franck-Dernoncourt  Ok, Got it! Thanks. But again I have below two doubts

1. When we use pretrained embeddings(which should have millions of words), it works only for words which are in my dataset vocab(few thousands, suppose 1K). And I'm expecting new words(synonyms for words in my vocab) in my test set, its most likely to fail on those. How to tackle this?

2. We use pre-trained embeddings only when we rain the model or we use it during test? (I mean in serve mode- when chatbot is serving for the user)

**Comment by pegadoflavian** [comment]
Anyone facing a memory error while loading the word2vec model? Any suggestions on the amount of memory (RAM) i need to make sure things don't crash? I'm using the GoogleNews-vectors-negative300.bin for the word embeddings.

**Comment by pldelisle** [comment]
I was running the script eith Google's pre-trained word vectors on a server with 24 GB of RAM and pretty much all the RAM was filled up.

**Comment by Psycho7** [comment]
For Python3, you should code like this:
```
        if FLAGS.word2vec:
            # initial matrix with random uniform
            initW = np.random.uniform(-0.25,0.25,(len(vocab_processor.vocabulary_), FLAGS.embedding_dim))
            # load any vectors from the word2vec
            print("Load word2vec file {}\n".format(FLAGS.word2vec))
            with open(FLAGS.word2vec, "rb") as f:
                header = f.readline()
                vocab_size, layer1_size = map(int, header.split())
                binary_len = np.dtype('float32').itemsize * layer1_size
                for line in range(vocab_size):
                    print(line)
                    word = []
                    while True:
                        ch = f.read(1).decode('latin-1')
                        if ch == ' ':
                            word = ''.join(word)
                            break
                        if ch != '\n':
                            word.append(ch)
                    print(word)
                    idx = vocab_processor.vocabulary_.get(word)
                    if idx != 0:
                        initW[idx] = np.fromstring(f.read(binary_len), dtype='float32')
                    else:
                        f.read(binary_len)
            sess.run(cnn.W.assign(initW))
```
And it really cost me a lot of time to figure it out... 😞

**Comment by peveloper** [comment]
Also running on a cluster and facing a MemoryError when loading the Google pre trained word vectors

**Comment by junchaozheng** [comment]
Also MemoryError when loading Word2Vec. 

Load word2vec file ./../../git_repo/style_transfer/data/GoogleNews-vectors-negative300.bin
Killed: 9

**Comment by naveenjafer** [comment]
@j314erre The code in the train.py that you have created in your gist seems to be using the load_data_and_labels function from data_helpers, but you have not fed the path of the positive_data_file and negative_data_file flags as it has been done in the original trian.py. Why?

**Comment by naveenjafer** [comment]
Anyone who is looking to Use Multi class classification with pre-trained Word2Vec, feel free to use this consolidated fork https://github.com/naveenjafer/cnn-text-classification-tf that builds on all the work done by the people here.

**Comment by hkhatod** [comment]
Has anyone tried to do visulization on cnn classification ? Which variable are you using to visualize

**Comment by monk1337** [comment]
I was facing same issue so I wrote detailed tutorial on that , check it out  this notebook how to Use Pre-trained word_embedding in Tensorflow

https://github.com/monk1337/word_embedding-in-tensorflow/blob/master/Use%20Pre-trained%20word_embedding%20in%20Tensorflow.ipynb
