### ISSUE TITLE
AttributeError: _parse_flags on running eval.py

### ISSUE THREAD

**Issue by sierra1bravo** [dennybritz/cnn-text-classification-tf#170]
I'm using python 2.7. I finished the training process without error. On running eval.py, I'm getting the following error:

$ ./eval.py --eval_train --checkpoint_dir="./runs/1546858759/checkpoints/"

Traceback (most recent call last):
  File "./eval.py", line 31, in <module>
    FLAGS._parse_flags()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 472, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags

Any information would be appreciated. Thanks in advance!

**Comment by modway** [comment]
I have getting the same problem with you!

**Comment by modway** [comment]
I am getting the same problem as you!

**Comment by BinHeRunning** [comment]
your problem has been solved in #158 @sierra1bravo @modway
