### ISSUE TITLE
AttributeError: type object 'NewBase' has no attribute 'is_abstract' using 0.8.0

### ISSUE THREAD

**Issue by servomac** [dennybritz/cnn-text-classification-tf#18]
Using tensorflow 0.8.0 (installed via `pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl`) I have the following error:

```
python3 train.py 
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 94, in <module>
    from tensorflow.python.platform import test
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/test.py", line 62, in <module>
    from tensorflow.python.framework import test_util
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/test_util.py", line 41, in <module>
    from tensorflow.python.platform import googletest
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/googletest.py", line 32, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/benchmark.py", line 112, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/benchmark.py", line 107, in __new__
    if not newclass.is_abstract():
AttributeError: type object 'NewBase' has no attribute 'is_abstract'
```

**Comment by servomac** [comment]
With the nightly build, it works. Good work!

**Comment by mayank-kgp** [comment]
@servomac 
I am facing same issue. 
Kindly help me.

**Comment by servomac** [comment]
@mayank-kgp which tensorflow version are you using? which python version?

Try with the last version.

**Comment by mayank-kgp** [comment]
@servomac I am using the command  for installing tensorflow - export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl
My python version is - 2.7.10

**Comment by mayank-kgp** [comment]
@servomac  It worked after sudo pip install six --upgrade --target="/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/"

**Comment by erwincoumans** [comment]
I just ran into the same issue with the latest Tensorflow wheel cpu/tensorflow-1.1.0-cp34-cp34m-linux_x86_64.whl in combination with OpenAI baselines.
