### ISSUE TITLE
AttributeError: _parse_flags

### ISSUE THREAD

**Issue by ghost** [dennybritz/cnn-text-classification-tf#181]
```
python3 ./eval.py --eval_train --checkpoint_dir="./runs/1459637919/checkpoints/"
Traceback (most recent call last):
  File "./eval.py", line 31, in <module>
    FLAGS._parse_flags()
  File "/home/raffaele/.local/lib/python3.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/raffaele/.local/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags
```

**Comment by x931890193** [comment]
me too

**Comment by WillAlex2017** [comment]
jist Comment on this line of code and the codes can run

**Comment by kailongzhao** [comment]
Tensorflow版本更新，只需用FLAGS.flag_values_dict()替换FLAGS._parse_flags()
